(ns logbook.all-highlighters
  (:require
    cljsjs.highlight
    cljsjs.highlight.langs.actionscript
    cljsjs.highlight.langs.apache
    cljsjs.highlight.langs.applescript
    cljsjs.highlight.langs.asciidoc
    cljsjs.highlight.langs.bash
    cljsjs.highlight.langs.clojure-repl
    cljsjs.highlight.langs.clojure
    cljsjs.highlight.langs.coffeescript
    cljsjs.highlight.langs.cpp
    cljsjs.highlight.langs.cs
    cljsjs.highlight.langs.css
    cljsjs.highlight.langs.d
    cljsjs.highlight.langs.dart
    cljsjs.highlight.langs.delphi
    cljsjs.highlight.langs.diff
    cljsjs.highlight.langs.elixir
    cljsjs.highlight.langs.erb
    cljsjs.highlight.langs.erlang-repl
    cljsjs.highlight.langs.erlang
    cljsjs.highlight.langs.fsharp
    cljsjs.highlight.langs.go
    cljsjs.highlight.langs.groovy
    cljsjs.highlight.langs.haml
    cljsjs.highlight.langs.handlebars
    cljsjs.highlight.langs.haskell
    cljsjs.highlight.langs.haxe
    cljsjs.highlight.langs.http
    cljsjs.highlight.langs.ini
    cljsjs.highlight.langs.java
    cljsjs.highlight.langs.javascript
    cljsjs.highlight.langs.json
    cljsjs.highlight.langs.less
    cljsjs.highlight.langs.lisp
    cljsjs.highlight.langs.livescript
    cljsjs.highlight.langs.lua
    cljsjs.highlight.langs.makefile
    cljsjs.highlight.langs.markdown
    cljsjs.highlight.langs.mathematica
    cljsjs.highlight.langs.matlab
    cljsjs.highlight.langs.mercury
    cljsjs.highlight.langs.nginx
    cljsjs.highlight.langs.nimrod
    cljsjs.highlight.langs.objectivec
    cljsjs.highlight.langs.ocaml
    cljsjs.highlight.langs.perl
    cljsjs.highlight.langs.php
    cljsjs.highlight.langs.powershell
    cljsjs.highlight.langs.python
    cljsjs.highlight.langs.r
    cljsjs.highlight.langs.ruby
    cljsjs.highlight.langs.rust
    cljsjs.highlight.langs.scala
    cljsjs.highlight.langs.scheme
    cljsjs.highlight.langs.scss
    cljsjs.highlight.langs.smalltalk
    cljsjs.highlight.langs.sml
    cljsjs.highlight.langs.sql
    cljsjs.highlight.langs.swift
    cljsjs.highlight.langs.tcl
    cljsjs.highlight.langs.tex
    cljsjs.highlight.langs.typescript
    cljsjs.highlight.langs.vala
    cljsjs.highlight.langs.vbnet
    cljsjs.highlight.langs.vbscript
    cljsjs.highlight.langs.verilog
    cljsjs.highlight.langs.vhdl
    cljsjs.highlight.langs.x86asm
    cljsjs.highlight.langs.xml))
